name: Bun Demo
run-name: Bun github action Demo
on: [push]
jobs:
  bun-demo:
    runs-on: ubuntu-latest
    name: Bun Demo
    steps:
      - uses: oven-sh/setup-bun@v1
      - run: bun ./main.ts
      
