name: Bun Demo
run-name: Bun GitHub Action Demo

on: [push]

jobs:
  bun-demo:
    runs-on: ubuntu-latest
    name: Bun Demo
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Bun version
        run: bun -v

      - name: List files and print working directory
        run: |
          ls
          pwd

      - name: Run a simple JavaScript script
        run: bun main.ts
